// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ashwinyue/dcp/internal/apiserver/biz/v1/post (interfaces: PostBiz)
//
// Generated by this command:
//
//	mockgen -destination mock_post.go -package post github.com/ashwinyue/dcp/internal/apiserver/biz/v1/post PostBiz
//

// Package post is a generated GoMock package.
package post

import (
	context "context"
	reflect "reflect"

	v1 "github.com/ashwinyue/dcp/pkg/api/apiserver/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockPostBiz is a mock of PostBiz interface.
type MockPostBiz struct {
	ctrl     *gomock.Controller
	recorder *MockPostBizMockRecorder
	isgomock struct{}
}

// MockPostBizMockRecorder is the mock recorder for MockPostBiz.
type MockPostBizMockRecorder struct {
	mock *MockPostBiz
}

// NewMockPostBiz creates a new mock instance.
func NewMockPostBiz(ctrl *gomock.Controller) *MockPostBiz {
	mock := &MockPostBiz{ctrl: ctrl}
	mock.recorder = &MockPostBizMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostBiz) EXPECT() *MockPostBizMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPostBiz) Create(ctx context.Context, rq *v1.CreatePostRequest) (*v1.CreatePostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rq)
	ret0, _ := ret[0].(*v1.CreatePostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPostBizMockRecorder) Create(ctx, rq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostBiz)(nil).Create), ctx, rq)
}

// Delete mocks base method.
func (m *MockPostBiz) Delete(ctx context.Context, rq *v1.DeletePostRequest) (*v1.DeletePostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, rq)
	ret0, _ := ret[0].(*v1.DeletePostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockPostBizMockRecorder) Delete(ctx, rq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostBiz)(nil).Delete), ctx, rq)
}

// Get mocks base method.
func (m *MockPostBiz) Get(ctx context.Context, rq *v1.GetPostRequest) (*v1.GetPostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, rq)
	ret0, _ := ret[0].(*v1.GetPostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPostBizMockRecorder) Get(ctx, rq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPostBiz)(nil).Get), ctx, rq)
}

// List mocks base method.
func (m *MockPostBiz) List(ctx context.Context, rq *v1.ListPostRequest) (*v1.ListPostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, rq)
	ret0, _ := ret[0].(*v1.ListPostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPostBizMockRecorder) List(ctx, rq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPostBiz)(nil).List), ctx, rq)
}

// Update mocks base method.
func (m *MockPostBiz) Update(ctx context.Context, rq *v1.UpdatePostRequest) (*v1.UpdatePostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rq)
	ret0, _ := ret[0].(*v1.UpdatePostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPostBizMockRecorder) Update(ctx, rq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPostBiz)(nil).Update), ctx, rq)
}
