// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package nightwatch

import (
	"github.com/ashwinyue/dcp/internal/nightwatch/biz"
	"github.com/ashwinyue/dcp/internal/nightwatch/pkg/validation"
	"github.com/ashwinyue/dcp/internal/pkg/server"
)

import (
	_ "github.com/ashwinyue/dcp/internal/nightwatch/watcher/all"
)

// Injectors from wire.go:

func InitializeWebServer(config *Config) (server.Server, error) {
	string2 := config.ServerMode
	iStore, err := ProvideStoreWithMongo(config)
	if err != nil {
		return nil, err
	}
	bizBiz := biz.NewBiz(iStore)
	validator := validation.New(iStore)
	serverConfig := &ServerConfig{
		cfg: config,
		biz: bizBiz,
		val: validator,
	}
	serverServer, err := NewWebServer(string2, serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
