// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ashwinyue/dcp/internal/apiserver/biz (interfaces: IBiz)
//
// Generated by this command:
//
//	mockgen -destination mock_biz.go -package biz github.com/ashwinyue/dcp/internal/apiserver/biz IBiz
//

// Package biz is a generated GoMock package.
package biz

import (
	reflect "reflect"

	post "github.com/ashwinyue/dcp/internal/apiserver/biz/v1/post"
	user "github.com/ashwinyue/dcp/internal/apiserver/biz/v1/user"
	gomock "go.uber.org/mock/gomock"
)

// MockIBiz is a mock of IBiz interface.
type MockIBiz struct {
	ctrl     *gomock.Controller
	recorder *MockIBizMockRecorder
	isgomock struct{}
}

// MockIBizMockRecorder is the mock recorder for MockIBiz.
type MockIBizMockRecorder struct {
	mock *MockIBiz
}

// NewMockIBiz creates a new mock instance.
func NewMockIBiz(ctrl *gomock.Controller) *MockIBiz {
	mock := &MockIBiz{ctrl: ctrl}
	mock.recorder = &MockIBizMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBiz) EXPECT() *MockIBizMockRecorder {
	return m.recorder
}

// PostV1 mocks base method.
func (m *MockIBiz) PostV1() post.PostBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostV1")
	ret0, _ := ret[0].(post.PostBiz)
	return ret0
}

// PostV1 indicates an expected call of PostV1.
func (mr *MockIBizMockRecorder) PostV1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostV1", reflect.TypeOf((*MockIBiz)(nil).PostV1))
}

// UserV1 mocks base method.
func (m *MockIBiz) UserV1() user.UserBiz {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserV1")
	ret0, _ := ret[0].(user.UserBiz)
	return ret0
}

// UserV1 indicates an expected call of UserV1.
func (mr *MockIBizMockRecorder) UserV1() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserV1", reflect.TypeOf((*MockIBiz)(nil).UserV1))
}
