-- SMS批处理表结构
CREATE TABLE `nw_sms_batch` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `batch_id` varchar(100) NOT NULL DEFAULT '' COMMENT 'SMS批次ID',
  `user_id` varchar(100) NOT NULL DEFAULT '' COMMENT '创建人',
  `scope` varchar(256) NOT NULL DEFAULT 'default' COMMENT 'SMS批次作用域',
  `name` varchar(255) NOT NULL DEFAULT '' COMMENT 'SMS批次名称',
  `description` varchar(256) NOT NULL DEFAULT '' COMMENT 'SMS批次描述',
  `campaign_id` varchar(100) NOT NULL DEFAULT '' COMMENT '运营活动ID',
  `campaign_name` varchar(255) NOT NULL DEFAULT '' COMMENT '运营活动名称',
  `marketing_program_id` varchar(100) DEFAULT NULL COMMENT '市场营销程序ID',
  `task_id` varchar(100) NOT NULL DEFAULT '' COMMENT '任务ID',
  `table_name` varchar(255) NOT NULL DEFAULT '' COMMENT 'Table Storage名称',
  `content_id` varchar(100) DEFAULT NULL COMMENT '短信模板内容ID',
  `content` text COMMENT '短信模板内容',
  `content_signature` varchar(100) DEFAULT NULL COMMENT '短信模板签名',
  `url` text COMMENT '短信模板包含的用户可点击的长链接',
  `combine_member_id_with_url` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否开启短链返回memberId',
  `auto_trigger` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否自动触发',
  `schedule_time` datetime DEFAULT NULL COMMENT 'Campaign Management的活动调度时间',
  `ext_code` int(11) NOT NULL DEFAULT '0' COMMENT '短信扩展码',
  `task_code` varchar(100) DEFAULT NULL COMMENT '任务代码，用于判断队列消息是否同一批次',
  `provider_type` varchar(32) NOT NULL DEFAULT 'WE' COMMENT '短信服务提供商类型',
  `message_type` varchar(32) NOT NULL DEFAULT 'SMS' COMMENT '消息类型(SMS/MMS)',
  `message_category` varchar(32) DEFAULT NULL COMMENT '短信类别(普通短信/营销短信)',
  `region` varchar(32) DEFAULT NULL COMMENT '区域',
  `source` varchar(32) DEFAULT NULL COMMENT '来源',
  `watcher` varchar(255) NOT NULL DEFAULT 'smsbatch' COMMENT 'nightwatch watcher 名字',
  `suspend` tinyint(4) NOT NULL DEFAULT '0' COMMENT '是否挂起（1 挂起，0 不挂起）',
  `params` longtext COMMENT 'SMS批次参数',
  `results` longtext COMMENT 'SMS批次执行结果',
  `status` varchar(32) NOT NULL DEFAULT 'Pending' COMMENT 'SMS批次状态',
  `conditions` longtext COMMENT 'SMS批次运行状态',
  `current_state` varchar(32) NOT NULL DEFAULT 'Initial' COMMENT '当前状态机状态',
  `current_phase` varchar(32) DEFAULT NULL COMMENT '当前执行阶段',
  `preparation_retries` int(11) NOT NULL DEFAULT '0' COMMENT '准备阶段重试次数',
  `delivery_retries` int(11) NOT NULL DEFAULT '0' COMMENT '发送阶段重试次数',
  `started_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'SMS批次开始时间',
  `ended_at` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'SMS批次结束时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_batch_id` (`batch_id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_scope` (`scope`),
  KEY `idx_campaign_id` (`campaign_id`),
  KEY `idx_status` (`status`),
  KEY `idx_current_state` (`current_state`),
  KEY `idx_watcher` (`watcher`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='SMS批处理任务表';

-- 添加索引以优化查询性能
CREATE INDEX `idx_status_state` ON `nw_sms_batch` (`status`, `current_state`);
CREATE INDEX `idx_schedule_time` ON `nw_sms_batch` (`schedule_time`);
CREATE INDEX `idx_task_code` ON `nw_sms_batch` (`task_code`);