# YouZan Order Watcher Configuration Example
# This configuration shows how to set up the YouZan order processing watcher

# Environment variables to set (recommended):
# export YOUZAN_API_BASE_URL="https://open.youzan.com"
# export YOUZAN_APP_ID="your_app_id_here"
# export YOUZAN_APP_SECRET="your_app_secret_here"
# export YOUZAN_API_TIMEOUT="30"  # seconds

# Watcher configuration
watcher:
  name: "youzanorder"
  enabled: true
  # Runs every 5 minutes
  spec: "0 */5 * * * *"
  
  # Processing configuration
  processing:
    max_workers: 10
    batch_size: 100
    
    # Rate limiting (QPS)
    rate_limits:
      fetch: 10
      validate: 20
      enrich: 15
      process: 25
    
    # Retry configuration
    retry:
      max_retries: 3
      timeout: 7200  # 2 hours in seconds
      
  # Job scopes to monitor
  scopes:
    - "youzanorder"
  
  # Statuses to process
  statuses:
    - "Pending"
    - "Fetching"
    - "Fetched"
    - "Validating"
    - "Validated"
    - "Enriching"
    - "Enriched"
    - "Processing"

# Database configuration
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "dcp_user"
  password: "dcp_password"
  database: "dcp_nightwatch"

# Logging configuration
logging:
  level: "info"
  format: "json"
  
# Monitoring configuration
monitoring:
  enabled: true
  metrics:
    - "orders_processed_total"
    - "orders_failed_total"
    - "processing_duration"
    - "api_requests_total"
    
# Example job creation
example_job:
  name: "YouZan Order Processing Job"
  scope: "youzanorder"
  watcher: "youzanorder"
  status: "Pending"
  metadata:
    start_time: "2024-01-01T00:00:00Z"
    end_time: "2024-01-01T23:59:59Z"
    page_size: 100
    order_status: "PAID" 