// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *MessageBatchJob) Default() {
}

func (x *MessageBatchJobParams) Default() {
}

func (x *MessageBatchJobResults) Default() {
}

func (x *MessageBatchJobCondition) Default() {
}

func (x *CreateMessageBatchJobRequest) Default() {
}

func (x *CreateMessageBatchJobResponse) Default() {
}

func (x *UpdateMessageBatchJobRequest) Default() {
}

func (x *UpdateMessageBatchJobResponse) Default() {
}

func (x *DeleteMessageBatchJobRequest) Default() {
}

func (x *DeleteMessageBatchJobResponse) Default() {
}

func (x *GetMessageBatchJobRequest) Default() {
}

func (x *GetMessageBatchJobResponse) Default() {
}

func (x *ListMessageBatchJobRequest) Default() {
}

func (x *ListMessageBatchJobResponse) Default() {
}
