// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *SmsBatch) Default() {
}

func (x *CreateSmsBatchRequest) Default() {
}

func (x *CreateSmsBatchResponse) Default() {
}

func (x *UpdateSmsBatchRequest) Default() {
}

func (x *UpdateSmsBatchResponse) Default() {
}

func (x *DeleteSmsBatchRequest) Default() {
}

func (x *DeleteSmsBatchResponse) Default() {
}

func (x *GetSmsBatchRequest) Default() {
}

func (x *GetSmsBatchResponse) Default() {
}

func (x *ListSmsBatchRequest) Default() {
}

func (x *ListSmsBatchResponse) Default() {
}
